project:
  type: website
  output-dir: docs

website:
  title: "Lab 6"
  navbar:
    left:
      - href: Lab6.html
        text: Home
      - href: hyperparameter-tuning.html
        text: Second Page

format:
  html:
    self-contained: true


